# Generated by Django 4.2.4 on 2023-08-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_service_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
