# Generated by Django 4.2.4 on 2023-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_contact_rendez_vous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
