# Generated by Django 4.2.4 on 2023-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
