# Generated by Django 4.2.4 on 2023-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_categorie_description_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='background_image',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
