# Generated by Django 4.2.4 on 2023-08-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_categorie_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='order_on_home',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='background_image',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.CharField(max_length=64),
        ),
    ]
