# Generated by Django 4.2.4 on 2023-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_categorie_order_on_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='order_on_home',
            field=models.IntegerField(unique=True),
        ),
    ]
