# Generated by Django 4.2.4 on 2023-08-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_about_about_paragraphes'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='lien_facebook',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='lien_insta',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='lien_tiktok',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='mail',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='nom_facebook',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='nom_insta',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='nom_tiktok',
            field=models.CharField(default=' ', max_length=64),
        ),
        migrations.AddField(
            model_name='about',
            name='numero',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
