# Generated by Django 4.2.4 on 2023-08-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_about_lien_facebook_about_lien_insta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='mail',
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='info@makeup-yam.com', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='order',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='lien_facebook',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='lien_insta',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='lien_tiktok',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='nom_facebook',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='nom_insta',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='nom_tiktok',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='about',
            name='numero',
            field=models.CharField(max_length=64),
        ),
    ]
