# Generated by Django 4.2.4 on 2023-08-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_remove_about_mail_about_email_about_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='quote',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
