# Generated by Django 4.2.4 on 2023-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_pourquoi_moi_paragraphes'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pourquoi_moi_image',
            field=models.CharField(default=' ', max_length=64),
            preserve_default=False,
        ),
    ]
