# Generated by Django 4.2.4 on 2023-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_contact_date_heure_rendez_vous_date_heure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('image', models.CharField(max_length=64)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
    ]
