# Generated by Django 4.2.4 on 2023-08-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_alter_homecarousel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
