# Generated by Django 4.2.4 on 2023-08-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_rename_date_heure_contact_date_heure_envoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
